### ISSUE TITLE
upload failed: [FineUploader 4.1.0] Error when attempting to parse xhr response text (Unexpected token <) 

### ISSUE THREAD

**Issue by rob-ot-dot-be** [fabarea/media_upload#1]
I dont get a json respons when i upload a file (image)
The storage has been set to a valid storage in the backend.

I did change the rendering of the plugin: moved the inline JS to an external file loaded in the footer (Jquery is also in the footer) and set the variables as globals. this does work fine.

as response i get the complete html of the page where i added the fluidhelper.

I have no clue where to start debugging.

php 5.4
typo3 6.2 

debug :

[FineUploader 4.1.0] Received 1 files or inputs. 
[FineUploader 4.1.0] Attempting to validate image.
[FineUploader 4.1.0] Attempting to draw client-side image preview. 
[FineUploader 4.1.0] Attempting to determine if 2013-09-28 22.37.06.jpg can be rendered in this browser 
[FineUploader 4.1.0] Sending upload request for 0 
[FineUploader 4.1.0] '2013-09-28 22.37.06.jpg' is  able to be rendered in this browser 
[FineUploader 4.1.0] Moving forward with EXIF header parsing for '2013-09-28 
[FineUploader 4.1.0] EXIF Byte order is big endian 
[FineUploader 4.1.0] Found 10 APP1 directory entries 
[FineUploader 4.1.0] Successfully parsed some EXIF tags 
[FineUploader 4.1.0] xhr - server response received for 0
[FineUploader 4.1.0] responseText = 	<!DOCTYPE html> ...

**Comment by fabarea** [comment]
Old issue. Currently updating the extension to TYPO3 7 LTS.

**Comment by KlickUndKlar** [comment]
I've got a similar failure with TYPO3 9.5.5 

[Fine Uploader 5.10.1] Error when attempting to parse xhr response text (Unexpected token < in JSON at position 0)

Can you give me a hint to fix that?
