### ISSUE TITLE
Bug in extension-manual & 1 question

### ISSUE THREAD

**Issue by freeATweb** [fabarea/media_upload#12]
Hi,

at first: awesome extension! :-)

There is a little bug in the manual:

```
         /** @var File $file */
           $file = $storage->addUploadedFile(
                    $uploadedFile->getTemporaryFileNameAndPath(),
                    $storage->getRootLevelFolder(),
                    $uploadedFile->getFileName(),
                    'changeName'
            );
```

has to be an array.

```
         /** @var File $file */
            $file = $storage->addUploadedFile(array(
                    $uploadedFile->getTemporaryFileNameAndPath(),
                    $storage->getRootLevelFolder(),
                    $uploadedFile->getFileName(),
                    'changeName'
              )
            );
```

One question occured to me while using media_upload in one of my extensions.

I integrated the media_upload as shown in the manual.
When i save the frontend-create-Form, an error occures, which I can't really solve on my own:

{"exception":"TYPO3\CMS\Core\Resource\Exception\InvalidFileNameException: File name  is invalid...

The storage folders in /typo3temp/MediaUpload/ are built correctly; the Parameters look OK too.
TCA, Domain Model, sql are correct.
Is it a bug in media_upload or am I missing something in integrating media_upload to my form or controller?

I am looking forward to your reply

Best regards

**Comment by Anubiso** [comment]
I stumbled upon the same error, 

you have to replace 
`/** @var File $file */
           $file = $storage->addUploadedFile(
                    $uploadedFile->getTemporaryFileNameAndPath(),
                    $storage->getRootLevelFolder(),
                    $uploadedFile->getFileName(),
                    'changeName'
            );`

with
`/** @var File $file */
           $file = $storage->addFile(
                    $uploadedFile->getTemporaryFileNameAndPath(),
                    $storage->getRootLevelFolder(),
                    $uploadedFile->getFileName(),
                    'changeName'
            );`

because the file is already uploaded to the server. Then it works (when everything else is configured correct)

**Comment by freeATweb** [comment]
it worked with $storage->addFile()

Thanks for your help!
