### ISSUE TITLE
Missing namespace Classes\ViewHelpers\Widget\Controller\UploadController.php

### ISSUE THREAD

**Issue by Kephson** [fabarea/media_upload#13]
Hi,
I'm missing the use of PermissionUtility in Classes\ViewHelpers\Widget\Controller\UploadController.php.
I added at the top:
<code>use Fab\Media\Utility\PermissionUtility;</code>
because the PermissionUtility is used in this class.

**Comment by fabarea** [comment]
Will be on the TER soon
