### ISSUE TITLE
Missing PermissionUtility

### ISSUE THREAD

**Issue by sunfish** [fabarea/media_upload#20]
Hi Fabien, 
it looks like Fab\Media\Utility\PermissionUtility is missing in this package.
Thanks for providing this utility file

**Comment by Kephson** [comment]
Hi sunfish, the namespace give the answer: the PermissionUtility you could find in the media extension, did you install it? I think in an older version of media this Class is missing.

**Comment by fabarea** [comment]
Class is [here](https://github.com/fabarea/media/blob/master/Classes/Utility/PermissionUtility.php) indeed and is only called if ```EXT:media``` has been installed and activated. 

```
if (ExtensionManagementUtility::isLoaded('media'))
```

**Comment by sunfish** [comment]
In my case EXT:media was not installed and PermissionUtility was called by Fab\MediaUpload\ViewHelpers\Widget\ControllerUploadController->getAllowedExtensions, if no allowedExtensions attribute but storage attribute was set. | sunfish

**Comment by fabarea** [comment]
@sunfish you're right. Could you test with this patch if it works for you?

**Comment by fabarea** [comment]
Let me know and I'll make a new TER bugfix release

**Comment by sunfish** [comment]
@fabarea thanks, this patch works, if media extension is not aivalable,

**Comment by fabarea** [comment]
Perfect, TER version has been updated.
