### ISSUE TITLE
uploaded-files not found

### ISSUE THREAD

**Issue by sunfish** [fabarea/media_upload#21]
Hi,
UploadFileService->sanitizeFileNameAndPath() wants to explode "UploadManager::UPLOAD_FOLDER" from $uploadedFileName.
But media_upload/Resources/Private/Assets/JavaScript/MediaUpload.js removes the UPLOAD_FOLDER part from the filePath.
_var basename = uri.replace("/typo3temp/MediaUpload/", "");
uploadedFiles.push(basename);_

So $sanitizedFileNameAndPath is empty, because _count($pathSegments)_ will not be 2.

**Comment by fabarea** [comment]
Not the only case apparently. For reference:

![image](https://cloud.githubusercontent.com/assets/620730/25014044/6bc8efde-2076-11e7-977a-f70f95684967.png)

**Comment by sunfish** [comment]
@
