### ISSUE TITLE
f:format.raw allowedExtensions

### ISSUE THREAD

**Issue by stephangrass** [fabarea/media_upload#25]
Hi,
in TYPO3 8 LTS the variable allowedExtensions must parsed by f:format.raw to prevent the conversion to the html-entities of the apostrophes. Without the result will be `var allowedExtensions= ['jpg&#039;,&#039;png'];`

**Comment by gromerop** [comment]
Hi.
I tried to parse the variable allowedExtensions in the following way, but the result was the same.

`<mu:widget.upload allowedExtensions="{f:format.raw(value; 'jpg,png,pdf,gif')}" storage="1" maximumSize="10" property="xxx"/>`

Finally, I have to modify EXT:media_upload/Resources/Private/Templates/ViewHelpers/Widget/Upload/Index.html

`<script>
  ...
  // Replaced this:
  // var allowedExtensions= ['{allowedExtensions}'];
  // ... by this:
  var allowedExtensions= ['{allowedExtensions->f:format.raw()}'];
  ...
</script>`

Would this change affect the versions prior to 8.7?

**Comment by Kephson** [comment]
I added a pull request with #43 because I had the same problem.

**Comment by Kephson** [comment]
This issue can be closed.
