### ISSUE TITLE
getUploadedFiles always returns an empty array

### ISSUE THREAD

**Issue by nyxos** [fabarea/media_upload#3]
After the successfull upload to the typo3temp I link to a different action. In the actions' controller I try to access the files as described in the manual with: $uploadedFiles = $this->uploadFileService->getUploadedFiles(); but it always returns empty.
Do I have to send some additional params to this action ?

Thanks and best regards,
Stefan.

**Comment by fabarea** [comment]
Do you have this hidden field in the DOM? What happen to its "value" after uploading a file. You must have a pretty up-to-date version of Media.

```
<input class="first" id="uploaded-files-images" name="tx_mediaupload_pi1[uploadedFiles][images]" value="" type="hidden">
```

After upload:

```
<input class="first" id="uploaded-files-images" name="tx_mediaupload_pi1[uploadedFiles][images]" value="53c7462e-a171-41c8-822f-3b996f3c9018-2014-10-01_1052.png" type="hidden">
```

**Comment by nyxos** [comment]
Thank you for your time!

I do have this hidden field, here it is before and after upload - it's not changing:
'<input id="uploaded-files-nxs" type="hidden" name="tx_mediaupload_pi1[uploadedFiles][nxs]" value=""/>'

'nxs' is the property I am using - with this ViewHelper:
'<mu:widget.upload storage="2" property="nxs" />'

**Comment by fabarea** [comment]
> and after upload - it's not changing

That's the problem. Do you have a JS error? I would need to double check whether I require jQuery in this build. Ideally it must be decoupled from jQuery.

**Comment by nyxos** [comment]
No JS error.
Here's the Console output of Fine Uploader:

´
[Fine Uploader 5.0.8] Parsing template
media_upload.min.js:16 [Fine Uploader 5.0.8] Template parsing complete
media_upload.min.js:16 [Fine Uploader 5.0.8] Rendering template in DOM.
media_upload.min.js:16 [Fine Uploader 5.0.8] Template rendering complete
´

**Comment by fabarea** [comment]
Here would be the source file where to debug at line 92.

https://github.com/fabarea/media_upload/blob/master/Resources/Public/Source/JavaScript/MediaUpload.js#L92

Pay attention, it must be edited in the build file

https://github.com/fabarea/media_upload/blob/master/Resources/Public/Build/media_upload.js#L11254

**Comment by nyxos** [comment]
Interesting: I replaced the min.js with the not-min.js and now I got following hidden field:
`<input id="uploaded-files-nxs" type="hidden" name="tx_mediaupload_pi1[uploadedFiles][nxs]" value="a1217b27-f7ab-4e58-823a-188cac7bdd9c-image.jpeg">``

But still: the ->uploadedFiles() is empty.

How can/should I pass this hiddenfield to my processAction ?

**Comment by fabarea** [comment]
That shouldn't be empty. When specifying the property in the VH, "nxs" in your case, it must also be told in the method as:

```
$uploadedFiles = $this->uploadFileService->getUploadedFiles('nxs')
```

I think it was discreetly mentioned in the example of the README.

**Comment by fabarea** [comment]
Let me know if that does not work for you.

**Comment by jensmarquardt** [comment]
For me the problem still exists. The VH returns the described hidden field, but the value is al
ways empty. Also `uploadedFileList` and `uploadedFiles` in [ShowUploadedController.php](https://github.com/fabarea/media_upload/blob/master/Classes/ViewHelpers/Widget/Controller/ShowUploadedController.php#L28-L34) are always empty.

**Comment by CHDuBar** [comment]
I had this problem when I deleted de line 38 in `Resources\Private\Templates\ViewHelpers\Widget\Upload\Index.html ` for remove the 'View' button . When set the line `<a class="view-btn btn btn-small btn-info hide" target="_blank">{f:translate(key: 'fineUploader.view')}</a>` again, I could have the uploaded files in array again
