### ISSUE TITLE
TYPO3 9.5.5 Statuscode 200 

### ISSUE THREAD

**Issue by freeATweb** [fabarea/media_upload#42]
Hello,

the extension worked fine with TYPO3 8.7 LTS, but after an update to TYPO3 9.5.5 I get an error:

[Fine Uploader 5.10.1] Error when attempting to parse xhr response text (Unexpected token < in JSON at position 0)

(Statuscode 200, server responded error. Reason unknown)

The /typo3temp/MediaUpload directory and subdirectories are not created.
(tested with chmod 777, [SYS][fileCreateMask] = 0777 and [SYS][folderCreateMask] = 0777)

I also tried to generate the respond-Uri with index.php?id=xx  (avoiding the new Routing Enhancers and Aspects) without success.

After a few hours of debugging I've still no idea where the problem is. 
Can you help me out?

Thanks a lot

**Comment by fabarea** [comment]
What is the exact respond of the XHR request?

> [Fine Uploader 5.10.1] Error when attempting to parse xhr response text (Unexpected token < in JSON at position 0)

I could assume some HTML junk in the response, such as PHP warning (or worst error) instead of crystal "pure" JSON response.

**Comment by freeATweb** [comment]
Thank you for your response!

The response is the the full HTML-Dokument of the page (no PHP-Warnings, debug-messages, ...)

Here's the console log of the Fine Uploader (debug : true):
[Fine Uploader 5.10.1] Parsing template
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Template parsing complete
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Rendering template in DOM.
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Template rendering complete
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Parsing template
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Template parsing complete
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Rendering template in DOM.
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Template rendering complete
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Parsing template
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Template parsing complete
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Rendering template in DOM.
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Template rendering complete
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Received 1 files.
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Attempting to validate image.
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Generating new thumbnail for 0
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Attempting to draw client-side image preview.
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Attempting to determine if myfile.pdf can be rendered in this browser
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] First pass: check type attribute of blob object.
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] myfile.pdf is not previewable in this browser per the blob's type attr
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Not previewable
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] Sending simple upload request for 0
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] xhr - server response received for 0
media_upload.1557746452.js:252 [Fine Uploader 5.10.1] responseText = <!DOCTYPE html> [complete HTML document]   Received response status 200 with body: [again the whole HTML document]


Typoscript is loaded, also the 
plugin.tx_mediaupload.features.requireCHashArgumentForActionArguments = 0 
to prevent the cHash-Valdiation of the Ajax-Call

**Comment by freeATweb** [comment]
Looks like media_upload isn't able to create the (Sub)folder and the temporary file, but neither the error-handling (permission checks) of media_upload nor the permissions-Validation of Fine Uploader are returning the permission failures

**Comment by rangerluke** [comment]
I have the same error. It seems, that the request payload variable "type" (for Page-Type) is not processed by typo3. Only the html page, on which the uploader is placed, is in the response.

**Comment by Kephson** [comment]
You only have to set paramsInBody to false; because the params are not attached to the URL, TYPO3 will render only the requested page. See #44 and #45

**Comment by abvdveen** [comment]
The same problem occurs when using a route enhancer of type PageTypeSuffix. Maybe related to https://forge.typo3.org/issues/88631. Tried adding a mapping for types 1386871773 and 1386871774, which are used for the ajax requests for adding and deleting media, but to no avail.

What fixes it in this case is replacing 
`return/index.php/.test(window.location.pathname)&&(a+=window.location.search),a`
with
`return '/'`
in media_upload.min.js
